// SPDX-License-Identifier: Apache-2.0

window.BIG_PERSONAS = Object.freeze({
  teacher: Object.freeze({
    id: "teacher",
    label: "1 · 探索教学图谱",
    accent: "#79a9ff",
    searchLabel: "搜索主题、课标科目、核心素养或教学节点",
    intro: Object.freeze({
      eyebrow: "给备课 Agent 的课标知识底座",
      title: "让你的备课 Agent 不再凭空编课",
      copy: "从一个真实问题出发，把主题结构、学科分工、学习关系与课标证据交给你已有的 Agent。",
    }),
    searchPlaceholder: "搜索主题、课标科目、核心素养或教学节点…",
    routeHeading: "从真实问题开始",
    subjectHeading: "课标学科 · 点击筛选",
    showAllLabel: "查看全部",
    subjectToggle: Object.freeze({ all: "全选", none: "全关" }),
    mapPanelLabel: "跨学科教学依赖地图",
    mapTitle: "高中跨学科教学节点与前置关系地图",
    mapDescription: "围绕八个跨学科主题，按学习进阶阶段排列；点击节点可查看节点作用、掌握证据、课标映射、前置关系和来源状态。",
    actions: Object.freeze({ label: "教学图谱操作", coverage: "课标依据", coverageReturn: "返回地图", data: "数据说明", connect: "了解 Agent 接入" }),
    terms: Object.freeze({
      performanceTask: "共同表现任务",
      nodeRole: "节点作用",
      diagnosticPrompt: "诊断问题",
      masteryEvidence: "掌握证据",
      prerequisite: "直接建立在",
      unlock: "解锁下一步",
      curriculumAlignment: "课标科目与核心素养",
      provenance: "来源与审阅边界",
    }),
  }),
  agent: Object.freeze({
    id: "agent",
    label: "2 · 接入备课 Agent",
    accent: "#c79cff",
    searchLabel: "搜索 theme_id、topic_id、subject_id 或关系",
    intro: Object.freeze({
      eyebrow: "先试用，再长期接入",
      title: "把可追溯的课程上下文交给你的 Agent",
      copy: "无需安装即可复制主题使用包；需要持续调用时，再配置本地只读 MCP。",
    }),
    searchPlaceholder: "搜索 theme_id、topic_id、subject_id 或关系…",
    routeHeading: "选择一个主题试用",
    subjectHeading: "subject_id · 点击筛选",
    showAllLabel: "全部主题",
    subjectToggle: Object.freeze({ all: "全选", none: "全关" }),
    mapPanelLabel: "只读课程本体关系图",
    mapTitle: "高中跨学科课程本体有向图",
    mapDescription: "按稳定 ID、实体类型和 prerequisite_id 到 topic_id 的方向读取主题、节点、邻接关系、课标映射与审阅边界。",
    actions: Object.freeze({ label: "Agent 接入操作", data: "数据说明", manifest: "Agent 清单", prompt: "启动提示", mcp: "配置示例", guide: "接入说明" }),
    terms: Object.freeze({
      performanceTask: "final_performance_task",
      nodeRole: "theme membership",
      diagnosticPrompt: "assessment_prompt",
      masteryEvidence: "mastery_evidence",
      prerequisite: "incoming prerequisites",
      unlock: "outgoing unlocks",
      curriculumAlignment: "curriculum_links",
      provenance: "source and review boundary",
    }),
  }),
});
