// SPDX-License-Identifier: Apache-2.0

window.BIG_PERSONAS = Object.freeze({
  teacher: Object.freeze({
    id: "teacher",
    label: "我是老师 · 教学图谱",
    accent: "#79a9ff",
    searchLabel: "搜索主题、课标科目、核心素养或教学节点",
    intro: Object.freeze({
      eyebrow: "先核对图谱，再和任意 AI 对话",
      title: "从学习关系到一节真正能上课的方案",
      copy: "探索真实问题、学科贡献、关键节点和前置关系；随后把 BunnyBook 链接发给你常用的任何 AI，无需安装。",
    }),
    searchPlaceholder: "搜索主题、课标科目、核心素养或教学节点…",
    routeHeading: "从真实问题开始",
    subjectHeading: "课标学科 · 点击筛选",
    showAllLabel: "查看全部",
    subjectToggle: Object.freeze({ all: "全选", none: "全关" }),
    mapPanelLabel: "跨学科教学依赖地图",
    mapTitle: "高中跨学科教学节点与前置关系地图",
    mapDescription: "围绕八个跨学科主题，按学习进阶阶段排列；点击节点可查看节点作用、掌握证据、课标映射、前置关系和来源状态。",
    actions: Object.freeze({ label: "教学图谱操作", coverage: "课标依据", coverageReturn: "返回地图", data: "数据说明", connect: "AI 如何使用" }),
    terms: Object.freeze({
      performanceTask: "共同表现任务",
      nodeRole: "节点作用",
      diagnosticPrompt: "诊断问题",
      masteryEvidence: "掌握证据",
      prerequisite: "直接建立在",
      unlock: "解锁下一步",
      curriculumAlignment: "课标科目与核心素养",
      provenance: "来源与审阅边界",
    }),
  }),
  agent: Object.freeze({
    id: "agent",
    label: "我是 AI / Agent",
    accent: "#c79cff",
    searchLabel: "搜索 theme_id、topic_id、subject_id 或关系",
    intro: Object.freeze({
      eyebrow: "先读公开协议，再按需取数",
      title: "把 BunnyBook 当作开放的课程信息源",
      copy: "从 /llms.txt 与 /agent/START-HERE.md 开始；公开链接足以完成第一次使用，MCP、Plugin 和 Skill 都只是可选加速层。",
    }),
    searchPlaceholder: "搜索 theme_id、topic_id、subject_id 或关系…",
    routeHeading: "选择一个主题读取",
    subjectHeading: "subject_id · 点击筛选",
    showAllLabel: "全部主题",
    subjectToggle: Object.freeze({ all: "全选", none: "全关" }),
    mapPanelLabel: "只读课程本体关系图",
    mapTitle: "高中跨学科课程本体有向图",
    mapDescription: "按稳定 ID、实体类型和 prerequisite_id 到 topic_id 的方向读取主题、节点、邻接关系、课标映射与审阅边界。",
    actions: Object.freeze({ label: "AI / Agent 操作", data: "数据说明", manifest: "图谱清单", prompt: "操作协议", mcp: "MCP 配置", guide: "可选接入" }),
    terms: Object.freeze({
      performanceTask: "final_performance_task",
      nodeRole: "theme membership",
      diagnosticPrompt: "assessment_prompt",
      masteryEvidence: "mastery_evidence",
      prerequisite: "incoming prerequisites",
      unlock: "outgoing unlocks",
      curriculumAlignment: "curriculum_links",
      provenance: "source and review boundary",
    }),
  }),
});
